### ISSUE TITLE
Add homebrew installation

### ISSUE THREAD

**Issue by JonDuffy** [santinic/how2#10]
Hey,

This looks great!

Would you be able to add a homebrew distribution for OS X?
http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x

cheers

**Comment by aweiler** [comment]
Hey,
You could do as I did:

     brew install node

and then

    npm install -g how2

That's not a direct home-brew install but maybe close enough?

**Comment by santinic** [comment]
yes, thanks @aweiler

**Comment by Ashtonian** [comment]
brew formula would be nice for people who don't have a reason to install node/npm.
