### ISSUE TITLE
Feature Request: Local Preferences

### ISSUE THREAD

**Issue by metiscus** [santinic/how2#11]
For nearly any issue of importance, there will be several answers. I would like the option to select my preference for a particular answer and be shown that answer automatically instead of the others for a particular query. This could be accomplished by storing a dictionary of queries with the preference value, or by tagging a priority number to the hash of the answer urls (treating untagged as a lower priority), each time an answer is marked up by me, it would increment the priority by 1 thus increasing the visibility of the answer in future queries.

**Comment by santinic** [comment]
@metiscus it's really interesting, please do it
