### ISSUE TITLE
SO search completely broken (deliberately?)

### ISSUE THREAD

**Issue by stupid-genius** [santinic/how2#120]
All `how2 -s <query>` queries fail with:
`Sorry, I cannot find any reasonable answer for your query.`

I really wanted to like this project, but it's always been buggy and now that the AI cash-grab is here, the main feature seems completely broken.  Is this going to be fixed or phased out?

**Comment by Oz-el-Ruso** [comment]
Same here. Even the "AI" feature is not the yellow of the egg.

**Comment by santinic** [comment]
I cannot make the Google search Nodejs module work anymore, it occasionally works but it's not as reliable as before. Btw everybody just uses the AI version all the time... when you learn to use it, there is no going back.
Anyhow, if you can find an alternative to reliably search Google via http, please show me or push PR
