### ISSUE TITLE
Hotkey: `O` to "open" a list item (Same as `Enter`/`l`)

### ISSUE THREAD

**Issue by stoutbeard** [santinic/how2#16]
Since you use `j`/`k` for movement, and `q` to "go back", I was expecting `o` to open the selected item in a list. I later discovered that the `l` key does the same, but for some reason my fingers wanted `o` to open the list item. Perhaps user configurable hotkeys would be nice? Or at least mention hotkeys in --help or in the readme?

**Comment by Foxboron** [comment]
I added `space` to open, felt more natural for me. But a config file or adding `o` shouldn't be hard.

**Comment by santinic** [comment]
"o" is a bit weird. Configurable hotkey is too hard. Hotkeys in --help: absolutely.
Also "b" to open browser to that link.

**Comment by Foxboron** [comment]
@santinic Not really no. A simple JSON config should be enough actually. I can maybe take a look at it. `o` is pretty normal for vi users tho.

**Comment by santinic** [comment]
json config sounds great, feel free to implement it man

**Comment by santinic** [comment]
"o", "space" and "b" are in 1.0.8. There is a status bar with hotkeys as well. 
"npm install -g how2" to update
