### ISSUE TITLE
Add proper credit to XKCD to comply with their license

### ISSUE THREAD

**Issue by codelitt** [santinic/how2#19]
In the interest of proper credit, should probably add a link and credit to the XKCD comic used [here](https://github.com/santinic/how2#why-)

Direct link to comic: https://xkcd.com/1168/

XKCD also provides a link for hotlinking/embedding which with attribution would be even better than just linking: http://imgs.xkcd.com/comics/tar.png 

XKCD's license requests/requires this: https://xkcd.com/license.html

**Comment by santinic** [comment]
omg, I appreciate your concern, but life is so short man

**Comment by anuragaryan** [comment]
attribute fast or die tryin'.
