### ISSUE TITLE
Gives error on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by noodlebreak** [santinic/how2#24]
I'm getting this:

    /usr/bin/env: node: No such file or directory

I installed it as instructed in your readme.

**Comment by shahkaran** [comment]
I am also getting the same error

**Comment by shahkaran** [comment]
@noodlebreak solved the issue .. you just need to symlink node 

ln -s /usr/bin/nodejs /usr/bin/node

found it thanks to http://stackoverflow.com/a/26320915

**Comment by santinic** [comment]
I should mention it in the docs. Thanks

**Comment by santinic** [comment]
It's in the readme now

**Comment by kapouer** [comment]
Or you install http://packages.ubuntu.com/xenial/nodejs-legacy
which does the same with the benefit of not screwing your ubuntu installation.

**Comment by santinic** [comment]
A symlink can definitely screw your entire life guys.
@kapouer, can you confirm the right way would be then:

$ sudo apt-get install nodejs npm nodejs-legacy
$ npm install -g how2

so i can put it in the Readme. Thanks

**Comment by kapouer** [comment]
Yes, it is.
I'm also trying to provide a new name for that package nodejs-legacy because nobody ever guessed it provided a node symlink.
