### ISSUE TITLE
Is possible to configure a proxy?

### ISSUE THREAD

**Issue by moscati** [santinic/how2#26]

**Comment by santinic** [comment]
It should take HTTPS_PROXY or HTTP_PROXY like all command line tools.
you need to make an alias though:
alias how2="HTTPS_PROXY='<your proxy>' how2"

**Comment by moscati** [comment]
I use Ubuntu. All other command line tools use http_proxy and  https_proxy.
I added HTTPS_PROXY or HTTP_PROXY and it works. 
Thanks

**Comment by santinic** [comment]
cool, happy to hear that
