### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by sargunv** [santinic/how2#29]
It would be nice to either read the user's default shell, or read a dotfile in the ~ or ~/.config/how2 directory to to set default language. 

I use the fish shell, so will never use the default language of Bash for how2.

Currently I've set an alias in my shell.

**Comment by panayotov** [comment]
Hi, can you set the alias?

in my .bashrc i have alias howto="how2 -l javascript" and it's not working

**Comment by sargunster** [comment]
I use Fish: 
```
function howto
  how2 -l fish $argv
end
```

I haven't tested bash, but it should be something like `alias howto='how2 -l fish'`

**Comment by panayotov** [comment]
Works perfect, thanks
