### ISSUE TITLE
System package management

### ISSUE THREAD

**Issue by danielquinn** [santinic/how2#3]
This is really nifty, but there's no way I would ever use sudo and let npm write to files and directories reserved for a real system-wide package manager.  If however, it was available as an apt package, RPM, or ebuild, then adoption is more likely.

**Comment by santinic** [comment]
you can try to do "npm install -g how2" without sudo if you get your local npm settings right.

https://docs.npmjs.com/getting-started/fixing-npm-permissions

I'll try to make ubuntu/homebrew packages, thanks.
