### ISSUE TITLE
link to alternatives?

### ISSUE THREAD

**Issue by omouse** [santinic/how2#30]
just a nice thought but I've included links to how2 and another tool in the docs for emacs-sos: https://github.com/omouse/emacs-sos#alternatives-to-sos-mode

not sure if you want to include links to emacs-sos or sx.el or other tools or libraries for using stackoverflow through a command-line or text editor.

**Comment by santinic** [comment]
I don't link to competitors buahauaua i couldn't care less, offer a pull request if you care thanks
