### ISSUE TITLE
Replace Google's API

### ISSUE THREAD

**Issue by pizzamaker** [santinic/how2#32]
Google is a known privacy violator and PRISM-contributor. It would be nice to have this search go through DuckDuckGo or (ideally if possible) searx.

**Comment by kirbyfan64** [comment]
Are...are you serious? I mean, I wouldn't mind the *option* to change search engines, but to *replace* it is a whole different story.

**Comment by santinic** [comment]
Duckduckgo, which instead is an NGO saving kids in Africa, doesn't provide a general search API (only some very limited instant-answer api).
@pizzamaker if you can write an html scraper for ddg in nodejs I will very happily add it to the codebase. Thanks for the suggestion
