### ISSUE TITLE
Ability to copy text from SPACE bar options

### ISSUE THREAD

**Issue by ashwinaj** [santinic/how2#33]
When I click on the space bar for more choices and select an option, a new "window" opens up. It would be nice to be able to copy the text from what's displayed.

Thanks!

**Comment by santinic** [comment]
yes @ashwinaj i was trying to do it, but it's not super easy. stay tuned

**Comment by saildata** [comment]
@santinic  Would it be easier to provide a hyperlink in the terminal?
