### ISSUE TITLE
Support for Cygwin/Babun

### ISSUE THREAD

**Issue by ajgassner** [santinic/how2#34]
- ANSI colors not working
- TypeError: undefined is not a function, see attached screenshot. Maybe https://github.com/TooTallNate/keypress/issues/19 is related.

Im using Babun v1.2.0, Node v0.12.2 on Windows 10

![image](https://cloud.githubusercontent.com/assets/2866145/13270173/92d1e10c-da8c-11e5-8f9a-059397760a22.png)

**Comment by Hammster** [comment]
maybe related to the same issue as with msys2 #28
