### ISSUE TITLE
Error: tunneling socket could not be established, cause=socket hang up : undefined

### ISSUE THREAD

**Issue by yejijie** [santinic/how2#40]
I have to use a http proxy to connect to Google.
I get an error:

```
Cannot connect to Google.
Error: Error on response:Error: tunneling socket could not be established, cause=socket hang up : undefined
```

Any idea please?

**Comment by danyshaanan** [comment]
Does this happen with the line mentioned in the readme?
```bash
alias how2="HTTPS_PROXY='your_proxy:8888' how2"
```
(https://github.com/santinic/how2#can-i-use-it-behind-proxy-)

**Comment by yejijie** [comment]
@danyshaanan Yes, but I use **socks5** proxy. Maybe this is the problem.

**Comment by sisrfeng** [comment]
>  socks5 proxy

+1 

My setting in zshrc
```bash
WF_ip='219.222.11.11:4080'
alias export_all_proxy="export ALL_PROXY=socks5://${WF_ip} ; export HTTPS_PROXY=https://${WF_ip} ; export HTTP_PROXY=http://${WF_ip} "

export_all_proxy
```

How to modify the zshrc to enable how2 ?
@yejijie 

Thx
