### ISSUE TITLE
`later` in 'updates.js' uses string comparison instead of int comparison.

### ISSUE THREAD

**Issue by danyshaanan** [santinic/how2#43]
https://github.com/santinic/how2/blob/master/lib/updates.js#L9-L17

```ls
 function later(a, b) {
        var as = a.split('.');
        var bs = b.split('.');
        for(var i=0; i<3; i++) {
            if(as[i] > bs[i])
                return true;
        }
        return false;
    }
later('1.0.9','1.0.10')
```

This returns true, as the string '9' is later lexicographically than the string '10'.

This can be resolved using semver as can be [seen here](https://tonicdev.com/56cda5321f78ba0c0009a1b6/56cda5321f78ba0c0009a1b7).

If this seems right, I could make the changes with a PR.

**Comment by santinic** [comment]
man you're amazing :) +1:  please do it if you have time. May magic goodness happen in your life

**Comment by danyshaanan** [comment]
Will do, probably later today :]
