### ISSUE TITLE
Undocumented "-i" option

### ISSUE THREAD

**Issue by danielkop** [santinic/how2#46]
In lib\index.js

```
if(argv.i) {
    how2.main(text, argv.l);
}
else {
    how2.magic(text, argv.l);
}
```

What's the purpose of -i? it's undocumented.
Should it be removed (along with how2.magic) or Added to readme.md and help?

**Comment by brunoceleste** [comment]
According to the README file, it seems the -i option will be used to search for your clipboard text.

```
Add automatic copy/paste from -i to command line
```

**Comment by danielkop** [comment]
So it should probably be on a separate branch until ready

**Comment by danielkop** [comment]
@santinic How would you like to advance this? Finish implementing the -i? Document it? Or move it to a separate branch for now?
