### ISSUE TITLE
Unable to Copy the Code

### ISSUE THREAD

**Issue by ahmadawais** [santinic/how2#55]
I am unable to copy the code from terminal when I am searching for another question with the `SPACE` and found an answer. Not able to select the code and copy it. Any help in there?

**Comment by danyshaanan** [comment]
Can you provide the exact steps you take to reproduce it? Including the line you run, the `SPACE` navigation, and the output you try to copy.

**Comment by ahmadawais** [comment]
See when I search for it, the first answer that I get, I can select and copy stuff from inside 

![](https://i.imgur.com/P2T9Zos.png)

But when I press `SPACE` for more answers and get to an answer, there I cannot select the text or copy anything.

![](https://i.imgur.com/P2T9Zos.png)

**Comment by danielkop** [comment]
@ahmadawais I think you pasted the same image twice.

Is this using ZSH? on which os?

**Comment by ahmadawais** [comment]
@danielkop Can you recheck the images, just refresh?

**Comment by ahmadawais** [comment]
Yes, I am using ZSH on Mac.

**Comment by h-ayat** [comment]
Same problem here.
ZSH on Arch linux

**Comment by smmoosavi** [comment]
Good repo, Good issue
Same issue. I use bash in terminator in ubuntu

**Comment by danyshaanan** [comment]
This is an issue with [blessed](https://www.npmjs.com/package/blessed), or with the way it is configured to run here. If you'd try to run the example code in the link above, you'll see that the text is not selectable.

**Comment by ahmadawais** [comment]
^Any solution for that?

**Comment by santinic** [comment]
@danyshaanan i think we need to add {mouse: true} to the options for all the blessed.box() 

I removed it cause I was getting weird wheel scrolling, but maybe is a better bug to have than not being able to copy-paste

**Comment by santinic** [comment]
it was {mouse:true}.  Either you can mouse scroll, or you can copy-paste. 

It's fixed in 1.0.9. Make sure you update with "npm install -g how2"

**Comment by h-ayat** [comment]
Thanx for quick reply and fix.
I've updated how2 to the latest version.
Now mouse clicks and scroll does nothing,
And there's a bug in selecting multi-line text, because background boxes get selected too.

I've attached a snapshot from the bug:

![how2](https://cloud.githubusercontent.com/assets/4332421/13426192/32eb9fbe-dfc1-11e5-875b-7e622d3452ec.jpg)

**Comment by danyshaanan** [comment]
@h-ayat I wouldn't call it a bug, as this is the intended behaviour of selection in the terminal, which is why I believe that it could not be resolved for the current view.

A possible alternative is to modify the way blessed is used here, and display the content of that window in full width without borders.

**Comment by ahmadawais** [comment]
^Same problem here. Thanks for the update but one cannot copy more than one line.

**Comment by danielkop** [comment]
A lot of terminals have a column select (or block select) feature.
With Ubuntu try holding Ctrl+Alt before you select, or Alt+Cmd if you're in iTerm.

**Comment by h-ayat** [comment]
@danyshaanan Thank you anyway.
@danielkop Very nice trick :+1:  Actually solved many problems other than this !

**Comment by danielkop** [comment]
@h-ayat It also works in a lot of text editors and IDEs. Block selection changed my life :grinning:

**Comment by santinic** [comment]
@danielkop such a nice trick! thanks, I'm putting it in the readme

**Comment by ahmadawais** [comment]
@danielkop Thanks for the tip, I never knew that.
