### ISSUE TITLE
How to uninstall how2?

### ISSUE THREAD

**Issue by geekjony** [santinic/how2#56]
I used npm to uninstall but failed.
` $ npm uninstall how2`
`npm WARN ENOENT ENOENT: no such file or directory, open '/Users/JonyMac/package.json'`
`npm WARN EPACKAGEJSON JonyMac No description`
`npm WARN EPACKAGEJSON JonyMac No repository field.`
`npm WARN EPACKAGEJSON JonyMac No README data`
`npm WARN EPACKAGEJSON JonyMac No license field.`

So how to remove how2 and its all dependencies？
Thanks.

**Comment by danyshaanan** [comment]
```bash
npm uninstall -g how2
```
