### ISSUE TITLE
Google certificate issue when use inside company firewall

### ISSUE THREAD

**Issue by quanghoc** [santinic/how2#58]
Is there a way to use `http` instead of `https` from google? I tried `-k` or `--skip-ssl-validation` but still got error:

```
Cannot connect to Google.
Error: Error on response:Error: unable to get local issuer certificate : undefined
```

When I disconnect from my company VPN, it's fine.

**Comment by santinic** [comment]
there is no --skip-ssl-validation, it shouldn't take much to implement it, can you do it ?

**Comment by cargoge** [comment]
this is the worst patch i could think of : dirty , simple and unsecure.
[forked unsafe repo](https://github.com/cargoge/how2/blob/master/lib/how2.js)

Be aware : the two lines i added disable https and ssl certificate validation
