### ISSUE TITLE
Make LICENSE DFSG compatible

### ISSUE THREAD

**Issue by onovy** [santinic/how2#59]
Hi,

i think license of this software is not DFSG compatible (https://people.debian.org/~bap/dfsg-faq.html + https://www.debian.org/social_contract.html#guidelines). I want to package it for Debian, but because of license I can't.

Can you consider changing license to any of:
https://wiki.debian.org/DFSGLicenses
please?

Thanks.

**Comment by danyshaanan** [comment]
:+1:

**Comment by danielkop** [comment]
:+1:

**Comment by santinic** [comment]
@onovy thanks, packages are very much appreciated. Unfortunately it seems that I cannot have non-military clauses and still be open-source by any definition. I'm a bit sad.

I changed to MIT, and published the npm module again.
