### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by pablobfonseca** [santinic/how2#77]
I'm not able to make any search, I'm getting this error:
![screen shot 2016-10-27 at 6 56 09 pm](https://cloud.githubusercontent.com/assets/5843859/19785164/2f505ef8-9c77-11e6-82e8-485d986e9084.png)

**OS:** MacOSX
**Node:** v7.0.0
**NPM:** 4.0.1

**Comment by daltonnyx** [comment]
I got this error too. I think this happened after i updated to node v7

**Comment by pablobfonseca** [comment]
Right, thanks @daltonnyx , I'm gonna wait for the PR, I think we're good to close it.

**Comment by ivanovaos** [comment]
Found a quick fix for later node. In devnull/transport/transport.js just changed two lines: 

line 8: var EventEmitter = require('events');
line 59: Transport.prototype.__proto__ = Object.create(EventEmitter.prototype);

Works fine after that!
