### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by Mykolaichenko** [santinic/how2#82]
Hello, 
Thanks for nice tool!
Here is DeprecationWarning: 
`|(node:65170) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.`

Kind regards

**Comment by klprint** [comment]
It seems as if there is nobody actively working on this project, anymore. This is really unfortunate, I also get the warning..

**Comment by kaustubhhiware** [comment]
+1. Same error.

**Comment by PaoloCifariello** [comment]
Fixed in #85.
